proxy-groups:
  - name: Match
    type: select  
    proxies: ["Global","DIRECT"]     
  - name: Guard
    type: select
    proxies: ["REJECT","DIRECT"]    
  - name: Global
    type: select
    proxies: ["HK","JP","SG","UN","Lab"]     
  - name: Emby
    type: select 
    proxies: "Global","DIRECT"]    
  - name: Apple
    type: select 
    proxies: ["US","HK","DIRECT","Global"]
  - name: Google
    type: select 
    proxies: ["Global"]
  - name: Game
    type: select 
    proxies: ["DIRECT","Lab","HK","TW","JP","SG","US","UN"]
  - name: PayPal
    type: select
    proxies: ["DIRECT","US","HK"]
  - name: Telegram
    type: select  
    proxies: ["Lab","Global","DIRECT"]    
  - name: Microsoft
    type: select  
    proxies: ["Global","DIRECT"]    
  - name: Netflix
    type: select
    proxies: ["SG","HK","TW","US"]  
  - name: HK
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    type: url-test
    interval: 300
    tolerance: 50
  - name: JP
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    type: select
    interval: 300
    tolerance: 50
  - name: US
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    type: select
    interval: 300
    tolerance: 50
  - name: TW
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    type: select
    interval: 300
    tolerance: 50
  - name: SG
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    type: select
    interval: 300
    tolerance: 50
  - name: UN
    include-all: true
    exclude-filter: (?i)港|HK|Hong Kong|HongKong|台|TW|Taiwan|日|JP|Japan|美|US|USA|United States|新|SG|Singapore
    type: select
    interval: 300
    tolerance: 50
  - name: Lab
    include-all: true
    filter: (?i)iplc|iepl|game|aia|ai
    type: select
rule-providers:
  Emby:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list
    path: ./ruleset/Emby.list
    interval: 86400

  PayPal:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
    path: ./ruleset/PayPal.list
    interval: 86400

  LinkedIn:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LinkedIn/LinkedIn.list
    path: ./ruleset/LinkedIn.list
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
    path: ./ruleset/OneDrive.list
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
    path: ./ruleset/Telegram.list
    interval: 86400

  Twitter:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
    path: ./ruleset/Twitter.list
    interval: 86400

  GoogleDrive:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.list
    path: ./ruleset/GoogleDrive.list
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
    path: ./ruleset/YouTube.list
    interval: 86400

  GoogleSearch:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleSearch/GoogleSearch.list
    path: ./ruleset/GoogleSearch.list
    interval: 86400

  TikTok:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
    path: ./ruleset/TikTok.list
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
    path: ./ruleset/OpenAI.list
    interval: 86400

  Gemini:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
    path: ./ruleset/Gemini.list
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
    path: ./ruleset/Spotify.list
    interval: 86400

  AbemaTV:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list
    path: ./ruleset/AbemaTV.list
    interval: 86400

  Bahamut:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
    path: ./ruleset/Bahamut.list
    interval: 86400

  TaiWanGood:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TaiWanGood/TaiWanGood.list
    path: ./ruleset/TaiWanGood.list
    interval: 86400

  ViuTV:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ViuTV/ViuTV.list
    path: ./ruleset/ViuTV.list
    interval: 86400

  LineTV:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.list
    path: ./ruleset/LineTV.list
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
    path: ./ruleset/Netflix.list
    interval: 86400

  GlobalMedia:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
    path: ./ruleset/GlobalMedia.list
    interval: 86400

  AsianMedia:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AsianMedia/AsianMedia.list
    path: ./ruleset/AsianMedia.list
    interval: 86400

  Advertising:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list
    path: ./ruleset/Advertising.list
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.list
    path: ./ruleset/Hijacking.list
    interval: 86400

  Global:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
    path: ./ruleset/Global.list
    interval: 86400

  China:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
    path: ./ruleset/China.list
    interval: 86400
rules:
  - "RULE-SET,LocalAreaNetwork,🎯 全球直连"
  - "RULE-SET,UnBan,🎯 全球直连"
  - "RULE-SET,BanAD,🛑 广告拦截"
  - "RULE-SET,BanProgramAD,🍃 应用净化"
  - "RULE-SET,GoogleFCM,📢 谷歌FCM"
  - "RULE-SET,GoogleCN,🎯 全球直连"
  - "RULE-SET,SteamCN,🎯 全球直连"
  - "RULE-SET,Bing,Ⓜ️ 微软Bing"
  - "RULE-SET,OneDrive,Ⓜ️ 微软云盘"
  - "RULE-SET,Microsoft,Ⓜ️ 微软服务"
  - "RULE-SET,Apple,🍎 苹果服务"
  - "RULE-SET,Telegram,📲 电报消息"
  - "RULE-SET,OpenAi,💬 OpenAi"
  - "RULE-SET,NetEaseMusic,🎶 网易音乐"
  - "RULE-SET,Epic,🎮 游戏平台"
  - "RULE-SET,Origin,🎮 游戏平台"
  - "RULE-SET,Sony,🎮 游戏平台"
  - "RULE-SET,Steam,🎮 游戏平台"
  - "RULE-SET,Nintendo,🎮 游戏平台"
  - "RULE-SET,YouTube,📹 油管视频"
  - "RULE-SET,Netflix,🎥 奈飞视频"
  - "RULE-SET,Bahamut,📺 巴哈姆特"
  - "RULE-SET,BilibiliHMT,📺 哔哩哔哩"
  - "RULE-SET,Bilibili,📺 哔哩哔哩"
  - "RULE-SET,ChinaMedia,🌏 国内媒体"
  - "RULE-SET,ProxyMedia,🌍 国外媒体"
  - "RULE-SET,ProxyGFWlist,🚀 节点选择"
  - "RULE-SET,ChinaDomain,🎯 全球直连"
  - "RULE-SET,ChinaCompanyIp,🎯 全球直连"
  - "RULE-SET,Download,🎯 全球直连"
  - "GEOIP,CN,🎯 全球直连"
  - "MATCH,🐟 漏网之鱼"
