proxy-groups:
  - name: Match
    type: select  
    proxies: ["Global","DIRECT"]     
  - name: Guard
    type: select
    proxies: ["REJECT","DIRECT"]    
  - name: Global
    type: select
    proxies: ["HK","JP","SG","UN","Lab"]     
  - name: Emby
    type: select 
    proxies: ["Global","DIRECT"]    
  - name: Apple
    type: select 
    proxies: ["US","HK","DIRECT","Global"]
  - name: Google
    type: select 
    proxies: ["Global"]
  - name: Game
    type: select 
    proxies: ["DIRECT","Lab","HK","TW","JP","SG","US","UN"]
  - name: PayPal
    type: select
    proxies: ["DIRECT","US","HK"]
  - name: Telegram
    type: select  
    proxies: ["Lab","Global","DIRECT"]    
  - name: Microsoft
    type: select  
    proxies: ["Global","DIRECT"]    
  - name: Netflix
    type: select
    proxies: ["SG","HK","TW","US"]  
    - name: Spotify
  type: select
  proxies: ["DIRECT", "HK", "TW", "UN"]

  - name: Disney+
    type: select
    proxies: ["SG", "US"]

  - name: YouTube
    type: select
    proxies: ["US", "HK", "SG", "JP"]

  - name: Bahamut
    type: select
    proxies: ["TW", "HK"]

  - name: Streaming
    type: select
    proxies: ["HK", "TW", "JP", "SG", "US", "UN"]

  - name: StreamingSE
    type: select
    proxies: ["DIRECT", "HK", "TW", "UN"]
   - name: Lab
    include-all: true
    filter: (?i)iplc|iepl|game|aia|ai|zz
    type: select   
  - name: HK
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    type: url-test
    interval: 300
    tolerance: 50
  - name: JP
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    type: select
    interval: 300
    tolerance: 50
  - name: US
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    type: select
    interval: 300
    tolerance: 50
  - name: TW
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    type: select
    interval: 300
    tolerance: 50
  - name: SG
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    type: select
    interval: 300
    tolerance: 50
  - name: UN
    include-all: true
    exclude-filter: (?i)港|HK|Hong Kong|HongKong|台|TW|Taiwan|日|JP|Japan|美|US|USA|United States|新|SG|Singapore
    type: select
    interval: 300
    tolerance: 50

rule-providers:
  BBC:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BBC/BBC.yaml
    path: ./ruleset/BBC.yaml
    interval: 86400

  Steam:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/Steam.yaml
    interval: 86400

  Xbox:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.yaml
    path: ./ruleset/Xbox.yaml
    interval: 86400

  Nintendo:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.yaml
    path: ./ruleset/Nintendo.yaml
    interval: 86400

  Download:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
    path: ./ruleset/Download.list
    interval: 86400

  Duolingo:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Duolingo/Duolingo.yaml
    path: ./ruleset/Duolingo.yaml
    interval: 86400

  TVer:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TVer/TVer.yaml
    path: ./ruleset/TVer.yaml
    interval: 86400

  niconico:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.yaml
    path: ./ruleset/Niconico.yaml
    interval: 86400

  Hulu:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hulu/Hulu.yaml
    path: ./ruleset/Hulu.yaml
    interval: 86400

  DisneyPlus:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
    path: ./ruleset/DisneyPlus.yaml
    interval: 86400
  Emby:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list
    path: ./ruleset/Emby.list
    interval: 86400

  PayPal:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
    path: ./ruleset/PayPal.list
    interval: 86400

  LinkedIn:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LinkedIn/LinkedIn.list
    path: ./ruleset/LinkedIn.list
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
    path: ./ruleset/OneDrive.list
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
    path: ./ruleset/Telegram.list
    interval: 86400

  Twitter:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
    path: ./ruleset/Twitter.list
    interval: 86400

  GoogleDrive:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.list
    path: ./ruleset/GoogleDrive.list
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
    path: ./ruleset/YouTube.list
    interval: 86400

  GoogleSearch:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleSearch/GoogleSearch.list
    path: ./ruleset/GoogleSearch.list
    interval: 86400

  TikTok:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
    path: ./ruleset/TikTok.list
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
    path: ./ruleset/OpenAI.list
    interval: 86400

  Gemini:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
    path: ./ruleset/Gemini.list
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
    path: ./ruleset/Spotify.list
    interval: 86400

  AbemaTV:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list
    path: ./ruleset/AbemaTV.list
    interval: 86400

  Bahamut:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
    path: ./ruleset/Bahamut.list
    interval: 86400

  TaiWanGood:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TaiWanGood/TaiWanGood.list
    path: ./ruleset/TaiWanGood.list
    interval: 86400

  ViuTV:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ViuTV/ViuTV.list
    path: ./ruleset/ViuTV.list
    interval: 86400

  LineTV:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.list
    path: ./ruleset/LineTV.list
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
    path: ./ruleset/Netflix.list
    interval: 86400

  GlobalMedia:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
    path: ./ruleset/GlobalMedia.list
    interval: 86400

  AsianMedia:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AsianMedia/AsianMedia.list
    path: ./ruleset/AsianMedia.list
    interval: 86400

  Advertising:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list
    path: ./ruleset/Advertising.list
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.list
    path: ./ruleset/Hijacking.list
    interval: 86400

  Global:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
    path: ./ruleset/Global.list
    interval: 86400

  China:
    type: http
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
    path: ./ruleset/China.list
    interval: 86400
rules:
  - RULE-SET,BBC,UN

  - RULE-SET,Emby,Emby

  - RULE-SET,LinkedIn,Global

  - RULE-SET,Steam,Game

  - RULE-SET,Xbox,Game

  - RULE-SET,Nintendo,Game

  - RULE-SET,PayPal,PayPal

  - RULE-SET,OneDrive,Microsoft

  - RULE-SET,Download,DIRECT

  - RULE-SET,Duolingo,YouTube

  - RULE-SET,Twitter,YouTube

  - RULE-SET,OpenAI,YouTube

  - RULE-SET,Telegram,Telegram

  - RULE-SET,Spotify,Spotify

  - RULE-SET,GoogleDrive,Google

  - RULE-SET,GoogleSearch,YouTube

  - RULE-SET,YouTube,YouTube

  - RULE-SET,Bahamut,Bahamut

  - RULE-SET,TaiwanGood,TW

  - RULE-SET,AbemaTV,JP

  - RULE-SET,TVer,JP

  - RULE-SET,niconico,JP

  - RULE-SET,ViuTV,HK

  - RULE-SET,LineTV,TW

  - RULE-SET,Hulu,US

  - RULE-SET,Netflix,Netflix

  - RULE-SET,DisneyPlus,Disney+

  - RULE-SET,Advertising,Guard

  - RULE-SET,Streaming,Streaming

  - RULE-SET,StreamingSE,StreamingSE

  - RULE-SET,Global,Global

  - RULE-SET,China,DIRECT

  - MATCH,Match
